services:
  db:
    image: postgres:17
    container_name: rangde_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: rangde
    ports:
      - "5432:5432"
    volumes:
      - rangde_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
volumes:
  rangde_postgres_data:

